### ISSUE TITLE
Named credentials are not available to Experience Cloud users

### ISSUE THREAD

**Issue by JFoxUK** [qwilio/qwil-salesforce-app#3]
Named credentials are not visible to experience cloud users despite adding the external credentials.

Updating the apex class to include the headers and endpoint allows it to work:
HttpRequest req = new HttpRequest();
        req.setEndpoint('https://REGION.qwil.io/entity-service/sys-api/sdk/sessions/create');
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('X-SYS-API-KEY', 'KEY HERE');
        req.setHeader('X-SYS-API-KEY-SECRET', 'SECRET HERE');

Suggestion, to move the api key, secret and endpoint to a custom metadata type and query that instead of the named credential when allowing for external users access. This could be achieved by querying the running user first.

**Comment by JFoxUK** [comment]
https://github.com/qwilio/qwil-salesforce-app/pull/4 may address the issue to your standard :)

**Comment by JFoxUK** [comment]
For clarity - it seems like they external users cannot see this Named Credential in Apex as per Debug logs (looking at reasons why), however they can see when using 'legacy' Named Credentials.

**Comment by JFoxUK** [comment]
Further update - to enable the use of named credentials of the external user, the profile/permission set of that Experience cloud user must have READ access on the User External Credentials object

**Comment by JFoxUK** [comment]
This - https://github.com/qwilio/qwil-salesforce-app/pull/6 - negates the code change should you prefer this method.

**Comment by shawnchin** [comment]
Thanks. https://github.com/qwilio/qwil-salesforce-app/pull/6 merged
