### ISSUE TITLE
Issue with static resource

### ISSUE THREAD

**Issue by JFoxUK** [qwilio/qwil-salesforce-app#5]
When running from Experience cloud:

qwilEmbed.js:1 Uncaught (in promise) TypeError: window.QwilApi is not a constructor
    at eval (qwilEmbed.js:1:2594)
    at Generator.next (<anonymous>)
    at A (qwilEmbed.js:1:1698)
    at l (qwilEmbed.js:1:1900)

**Comment by shawnchin** [comment]
This should be fixed with the latest release of qwil-iframe-api v0.2.4.

Thanks for working with us to debug this 🙇🏽
